FROM ubuntu:20.10

RUN apt-get update
RUN apt-get -y install wget
RUN wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.10.9/sratoolkit.2.10.9-ubuntu64.tar.gz

RUN tar xf sratoolkit.2.10.9-ubuntu64.tar.gz
ENV PATH="sratoolkit.2.10.9-ubuntu64/bin:$PATH"
RUN cd /usr/bin && ln -s /sratoolkit.2.10.9-ubuntu64/bin/* .

RUN mkdir /root/.ncbi 
ADD user-settings.mkfg /root/.ncbi
